GET http://localhost:3000/users

###

GET http://localhost:3000/users/6aa448d98794c8364660dd6b

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Angie2",
    "password": "fart6969"
}

###

DELETE http://localhost:3000/users/6aa449fb9009c5be71524b3c

###

PATCH http://localhost:3000/users/6aa44a179009c5be71524b43
Content-Type: application/json

{
    "username": "Zangie"
}